#!sh

awk 'BEGIN { print "<projects>"; i = 0 } { if ($0 ~ /] of  Project$/) { print "<project>\n\t<id>" substr($0, 3, 36) "</id>"; i = 0 }; if ($0 ~ /description / && i == 0) { print "\t<file>" substr($0, 16, length($0) - 17) "</file>\n</project>"; i++ } } END { print "</projects>" }' metaproject.pins > projects.xml
